### ISSUE TITLE
"Potentially unhandled rejection" error

### ISSUE THREAD

**Issue by brettstack** [systemjs/plugin-image#2]
Under certain conditions AdBlock is causing plugin-image to throw an error and stopping the rest of my app from loading:

```
Potentially unhandled rejection [3] [object Event] 
Error loading https://123abc.cloudfront.net/assets/img... as "assets/img/logo.svg!github:systemjs/plugin-image@0.1.0" from https://123abc.cloudfront.net/app/compon... (WARNING: non-Error used) 
[4]</</</</a<()system.js (line 4) 
t = "Potentially unhandled re...ARNING: non-Error used)" 
i()system.js (line 4) 
t = q { id=3, value="[object Event]\n Error lo...ar/nav-bar-directive.js", handled=false, more...} 
s()
```

How do I handle this? I'm loading using `import logo from 'assets/img/logo.svg!image';`. Will I need to resort to System.import? Ideally plugin-image (and plugin-css etc.) would handle this since it shouldn't be a fatal error if an image or stylesheet doesn't load.

**Comment by guybedford** [comment]
Thanks for posting. This does sound like it could be a bug. Any ideas how to better catch this error than https://github.com/systemjs/plugin-image/blob/master/image.js#L10 are welcome here.

**Comment by guybedford** [comment]
Actually sorry, yes it is a fatal error if an image doesn't load, just like it is a fatal error if a module doesn't load.

If you're looking for a more flexible loading method, then `System.import` with rejection is exactly the workflow.

**Comment by brettstack** [comment]
I understand it's a fatal error for a module to not load when it's a script, but images should be treated as optional. Just as it doesn't break your entire app when it can't find an image in <img src>. 99% of the time this is what you want it to do.

Stylesheets generally have more impact than an image, but I think they too should silently fail (resolve).

`img.onerror = resolve;`

**Comment by guybedford** [comment]
If you are loading images or stylesheets as part of your core module system, then the assumption must be that you absolutely need those resources present for the functioning of the code, just like any other module. If that is not the case, then do not use the module loader to load these resources, and there are lots of alternatives.

**Comment by brettstack** [comment]
Thanks, I'll try the System.import approach.
