### ISSUE TITLE
Static builds

### ISSUE THREAD

**Issue by guybedford** [systemjs/plugin-image#3]
Can we support this? Should we support this?

**Comment by tjaartvdwalt** [comment]
@guybedford, first off thank you for doing an amazing job with systemjs/jspm!

What would it mean exactly for this plugin to support static builds? Would the plugin inline the images?

**Comment by guybedford** [comment]
This would be for webpack-style image relocations. I don't think we want to complicate this project though after all from its simple dynamic loading use case.
